# Generated by Django 5.1.5 on 2025-02-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='10:42'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caretaker',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caretaker',
            name='experience',
            field=models.IntegerField(default='2 years'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caretaker',
            name='first_name',
            field=models.CharField(default='Mansa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caretaker',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='last_name',
            field=models.CharField(default='Tamang', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caretaker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
