# Generated by Django 5.1.5 on 2025-03-21 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
