# Generated by Django 5.1.5 on 2025-03-25 11:17

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='caretaker',
            old_name='image',
            new_name='gov_id',
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='specialty',
        ),
        migrations.AddField(
            model_name='caretaker',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='certification_docs',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='languages_spoken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='monthly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='police_clearance',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='preferred_locations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='previous_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caretaker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='working_days',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='experience',
            field=models.IntegerField(help_text='Years of experience'),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='specialties',
            field=models.ManyToManyField(related_name='caretakers', to='project.specialty'),
        ),
    ]
