# Generated by Django 5.1.5 on 2025-03-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_specialty_rename_image_caretaker_gov_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretaker',
            name='user',
        ),
    ]
