# Generated by Django 5.1.5 on 2025-04-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_booking_price_alter_booking_note_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
