# Generated by Django 5.1.5 on 2025-02-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_caretaker_created_at_caretaker_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretaker',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
    ]
