# Generated by Django 5.1.5 on 2025-03-25 12:00

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_caretaker_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretaker',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='name',
        ),
        migrations.AddField(
            model_name='specialty',
            name='specialty',
            field=models.CharField(blank=True, choices=[('Elder Care', 'Elder Care'), ('Medication Management', 'Medication Management'), ('Physical Therapy', 'Physical Therapy')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='address',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='certification_docs',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Upload Profile Certificate Documents'),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='gov_id',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Upload Profile Citizenship'),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='police_clearance',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Upload Profile Police Clearance'),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Upload Profile Picture'),
        ),
    ]
