# Generated by Django 5.1.5 on 2025-02-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_caretaker_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='first_name',
            field=models.CharField(default='2025-01-01 00:00:00+00:00', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caretaker',
            name='last_name',
            field=models.CharField(default='Tamang', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
