# Generated by Django 5.1.5 on 2025-02-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_caretaker_first_name_caretaker_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretaker',
            name='name',
        ),
    ]
