# Generated by Django 5.1.5 on 2025-03-15 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_caretakerbooking_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaretakerBooking',
        ),
    ]
