# Generated by Django 5.1.5 on 2025-02-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_caretaker_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caretaker',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='last_name',
        ),
        migrations.AlterModelTable(
            name='caretaker',
            table='project_caretaker',
        ),
    ]
