# Generated by Django 5.1.5 on 2025-03-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_booking_first_name_booking_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='last_name',
        ),
    ]
