# Generated by Django 5.1.5 on 2025-04-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_messsage_notification_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretaker',
            name='working_days',
        ),
    ]
