# Generated by Django 5.1.5 on 2025-02-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_first_name_caretaker_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='caretaker',
            table=None,
        ),
    ]
