# Generated by Django 5.1.5 on 2025-02-24 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_caretaker_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='bio',
            field=models.CharField(default='Experienced in elderly care services', max_length=250),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='username',
            field=models.CharField(default='2025-02-23 12:30:45+00:00', unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.caretaker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
