# Generated by Django 5.1.5 on 2025-03-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_booking_first_name_remove_booking_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default='misha', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(default='tamang', max_length=150),
            preserve_default=False,
        ),
    ]
