# Generated by Django 5.1.5 on 2025-02-24 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_caretaker_bio_caretaker_username_booking'),
    ]

    operations = [
    ]
