# Generated by Django 5.1.5 on 2025-04-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_booking_first_name_remove_booking_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretaker',
            name='password',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
