# Generated by Django 5.1.5 on 2025-04-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_remove_caretaker_password_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='password',
            field=models.CharField(default='secret@123', max_length=255),
            preserve_default=False,
        ),
    ]
