# Generated by Django 5.1.5 on 2025-02-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20250224_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretaker',
            name='bio',
            field=models.CharField(max_length=250),
        ),
    ]
