# Generated by Django 5.1.5 on 2025-02-24 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_caretaker_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
