# Generated by Django 5.1.5 on 2025-04-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_caretaker_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='NotificationCaretaker',
        ),
    ]
