# Generated by Django 5.1.5 on 2025-04-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_customuser_is_delete_delete_notificationcaretaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
