# Generated by Django 5.1.5 on 2025-02-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_customuser_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='role',
            field=models.CharField(default='caretaker'),
        ),
    ]
