# Generated by Django 5.1.5 on 2025-02-25 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_alter_customuser_first_name_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='user',
            field=models.OneToOneField(default='masa', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='role',
            field=models.CharField(default='caretaker', max_length=20),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
