# Generated by Django 5.1.5 on 2025-02-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_caretaker_user_alter_caretaker_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretaker',
            name='user',
        ),
    ]
