# Generated by Django 5.1.5 on 2025-02-26 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project', '0021_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caretaker',
            old_name='is_available',
            new_name='available',
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='caretaker',
            name='phone',
            field=models.CharField(default='2025-02-26 12:00:00+00:00', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caretaker',
            name='specialty',
            field=models.CharField(default='Child Care', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
