# Generated by Django 5.1.5 on 2025-02-26 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_rename_is_available_caretaker_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caretaker',
            old_name='available',
            new_name='is_available',
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.caretaker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
